language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
deploy:
  skip_cleanup: true
  on:
    repo: iamolegga/nestjs-cookie-session
    branch: master
  provider: npm
  email: iamolegga@gmail.com
  api_key:
    secure: tD4up9c5DIFzqLvKK5A5oolcDI7Grx87XnNKt2JlGFIZhmKRmhk24MNHuYQMO2b6LSlZGxzzhbix0eIbULQMknfRgFsxSaYobsad4q0NzU6Znkbao727T5m2eTxugRETCRSncSefz0+qfWsHGCIuAWtsd6fQ/oZCx/XTk0zpF/IKUDFRA7CtVPf0K9nJHDyxer8Zrw1evmU9lcUKEri7TZpcTXFki/9JMM3d0o0rqfJHkDdaRLNRI31GlDLzv+uiUcMv3ABKYIniz0CP5UoVVQI+ZUIZfAc8ki8OiMp/g6kieVrpjoql/O0Ic3oN3vlOZZvFTMuvLgqv5vyhxwjDnkNfqyQwhkUBPwDKR8t9FTyM2VlBXvNQzdSRyIgoV4tcp0Y9juyCAKYRwBqOdUnAsK0UlkzxFOrlbKur5bqm5gYnM3HdgeO0CUcoZhnY0lX+zE3wpfWlBLwOAkYyNS06m2/a5VDWe8LKwOujcpsd/iq4XxVDtVk9LqcMRsVhb16f7VvSE97T07HPhszPaEQ/pJYa01bmUdQbuEoKdRAJKMvRnBckMbajzdFwpj8Gs5PqGoYjLdbX7o3f4z9nMSkSTTiiP7J7tURKuZn+dHPFnk3Pw0CYkHAr6GOgWQ0Y4aBzk2Vv+2JgcPdFaqVsLkdH5yNRTRR4FSheHmReoxff/2Y=
script:
  - npm run build
  - npm run test
after_deploy:
  - npm run report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
